### ISSUE TITLE
[BUG] - asset check

### ISSUE THREAD

**Issue by SeanSierra-Patev** [CDCgov/phoenix#175]
running local via nextflow/docker

getting this error

ERROR ~ Error executing process > 'CDC_PHOENIX:PHOENIX_EXQC:ASSET_CHECK (1)'

Caused by:
  /media/sean/8TB1/Kleb/work/d0/9f6329accd8dda5218e9a8c2937673/db

 -- Check '.nextflow.log' file for details

```shell
Aug-06 12:17:27.707 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 2; name: CDC_PHOENIX:PHOENIX_EXQC:ASSET_CHECK (1); status: COMPLETED; exit: 0; error: -; workDir: /media/sean/8TB1/Kleb/work/d0/9f6329accd8dda5218e9a8c2937673]
Aug-06 12:17:27.710 [TaskFinalizer-2] DEBUG nextflow.processor.TaskProcessor - Handling unexpected condition for
  task: name=CDC_PHOENIX:PHOENIX_EXQC:ASSET_CHECK (1); work-dir=/media/sean/8TB1/Kleb/work/d0/9f6329accd8dda5218e9a8c2937673
  error [java.nio.file.AccessDeniedException]: /media/sean/8TB1/Kleb/work/d0/9f6329accd8dda5218e9a8c2937673/db
Aug-06 12:17:27.716 [TaskFinalizer-2] ERROR nextflow.processor.TaskProcessor - Error executing process > 'CDC_PHOENIX:PHOENIX_EXQC:ASSET_CHECK (1)'

Caused by:
  /media/sean/8TB1/Kleb/work/d0/9f6329accd8dda5218e9a8c2937673/db


java.nio.file.AccessDeniedException: /media/sean/8TB1/Kleb/work/d0/9f6329accd8dda5218e9a8c2937673/db
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:432)
	at java.base/java.nio.file.Files.newDirectoryStream(Files.java:472)
	at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:300)
	at java.base/java.nio.file.FileTreeWalker.next(FileTreeWalker.java:373)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2761)
	at nextflow.file.FileHelper.visitFiles(FileHelper.groovy:856)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
	at nextflow.processor.TaskProcessor.fetchResultFiles(TaskProcessor.groovy:1738)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
	at nextflow.processor.TaskProcessor.collectOutFiles(TaskProcessor.groovy:1665)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
	at nextflow.processor.TaskProcessor.collectOutputs(TaskProcessor.groovy:1540)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
	at nextflow.processor.TaskProcessor.collectOutputs(TaskProcessor.groovy:1521)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
	at nextflow.processor.TaskProcessor.finalizeTask(TaskProcessor.groovy:2386)
	at nextflow.processor.TaskPollingMonitor.finalizeTask(TaskPollingMonitor.groovy:686)
	at nextflow.processor.TaskPollingMonitor.safeFinalizeTask(TaskPollingMonitor.groovy:676)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:343)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:328)
	at groovy.lang.MetaClassImpl.doInvokeMethod(MetaClassImpl.java:1333)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1088)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1007)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:645)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:628)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethodSafe(InvokerHelper.java:82)
	at nextflow.processor.TaskPollingMonitor$_checkTaskStatus_lambda8.doCall(TaskPollingMonitor.groovy:666)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Aug-06 12:17:27.731 [TaskFinalizer-2] DEBUG nextflow.Session - Session aborted -- Cause: /media/sean/8TB1/Kleb/work/d0/9f6329accd8dda5218e9a8c2937673/db

``` 

the excecuted command was 
```shell
nextflow run cdcgov/phoenix -r v2.1.1 -profile docker -entry CDC_PHOENIX --create_ncbi_sheet --input 8_6samples.csv --kraken2db ~/Workdir/Phoenix_kraken_db/k2_standard_08gb_20240605/
```

**Comment by SeanSierra-Patev** [comment]
also getting this warning if that helps

WARN: Undocumented setting `docker.userEmulation` is not supported any more - please remove it from your config
